ALTER TABLE guests ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS conditions TEXT[] DEFAULT '{}';
ALTER TABLE guests ADD COLUMN IF NOT EXISTS allergies TEXT[] DEFAULT '{}';
ALTER TABLE guests ADD COLUMN IF NOT EXISTS consultation_reason TEXT;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS is_for_self BOOLEAN DEFAULT TRUE;
